export default {
  en: {
    language: "Language",
    label: "English",
    darkMode: "Dark mode",
    navigation: "Navigation",
    news: "News",
    solves: "Solves",
    general: "General",
    team: "Team",
    country: "Country",
    score: "Score",
    rulesButton: "Click here to go to the website with the rules",
    username: "Username",
    members: "Members",
    challenge: "Challenge",
    time: "Time",
    close: "Close",
    gettingInformations: "Getting informations",
    login: "Register / Login",
    logout: "Logout",
    gettingToken: "Getting token",
    gettingTokenInfo:
      "This token will be used to fork the submissions repository, to commit to it on your behalf and to make pull requests.",
    gettingUser: "Getting user data",
    gettingUserInfo: "Name and others info.",
    creatingFork: "Creating fork",
    creatingForkInfo: "Forking the submission repository.",
    createTeam: "Create team",
    joinTeam: "Join team",
    teamName: "Team name",
    teamCountries: "Team countries",
    submit: "Submit",
    fixErrors: "Please fix the following error(s):",
    teamPrivateKey: "Team private key",
    flagFound: "Flag found, submitted!",
    encodedTeam:
      "This is your team's private key. Share with your team so they can join the team!  This key is stored in the browser and is not linked to your GitHub account.",
    teamCreated: "Team created",
    saveYourTeamSecret: "Save <strong>NOW</strong> your team's private key!",
    router: {
      Home: "Home",
      Challenges: "Challenges",
      Rank: "Rank",
      Rules: "Rules",
      Settings: "Settings",
      Logged: "Getting informations",
      Faq: "FAQ"
    },
    errors: {
      teamName: "Invalid team name.",
      privateKey: "Private key is invalid.",
      maxMembers: "Invalid number of members. Up to {max} members are allowed."
    }
  },
  pt: {
    language: "Idioma",
    label: "Português (BR)",
    darkMode: "Modo escuro",
    navigation: "Navegação",
    news: "Notícias",
    solves: "Resolvidos",
    general: "Geral",
    team: "Time",
    country: "País",
    score: "Pontuação",
    rulesButton: "Clique aqui para ir ao site com as regras",
    username: "Username",
    members: "Membros",
    challenge: "Desafio",
    time: "Hora",
    close: "Fechar",
    gettingInformations: "Obtendo informações",
    login: "Registrar / Logar",
    logout: "Sair",
    gettingToken: "Obtendo token",
    gettingTokenInfo:
      "Esse token será usado para criar o fork do repositório de submissões, para fazer commits em seu nome e criar pull requests. Este token está armazenado no local storage, ou seja, não está vinculada a sua conta do GitHub.",
    gettingUser: "Obtendo dados do usuário",
    gettingUserInfo: "Nome e outras informações.",
    creatingFork: "Criando fork",
    creatingForkInfo: "Criando fork do repositório de submissões.",
    createTeam: "Criar time",
    joinTeam: "Juntar-se ao time",
    teamName: "Nome do time",
    teamCountries: "Países do time",
    submit: "Enviar",
    fixErrors: "Por favor, corrija o(s) seguinte(s) erro(s):",
    teamPrivateKey: "Chave privada do time",
    flagFound: "Flag encontrada, enviado!",
    encodedTeam:
      "Essa é  a chave privada da sua equipe. Compartilhe com sua equipe para que eles possam entrar na equipe! Esta chave está armazenada no seu navegador e não está vinculada a sua conta do GitHub.",
    teamCreated: "Time criado",
    saveYourTeamSecret:
      "Salve <strong>AGORA</strong> a chave privada do seu time!",
    router: {
      Home: "Início",
      Challenges: "Desafios",
      Rank: "Rank",
      Rules: "Regras",
      Settings: "Configurações",
      Logged: "Obtendo informações",
      Faq: "FAQ"
    },
    errors: {
      teamName: "Nome do time inválido.",
      privateKey: "Chave privada é inválida.",
      maxMembers:
        "Número de membros inválido. São permitidos até {max} membros."
    }
  }
};
