export default {
  en: {
    language: "Language",
    label: "English",
    darkMode: "Dark mode",
    navigation: "Navigation",
    news: "News",
    solves: "Solves",
    general: "General",
    team: "Team",
    country: "Country",
    score: "Score",
    rulesButton: "Click here to go to the website with the rules",
    username: "Username",
    members: "Members",
    challenge: "Challenge",
    time: "Time",
    close: "Close",
    gettingInformations: "Getting informations",
    login: "Login",
    logout: "Logout",
    gettingToken: "Getting token",
    gettingTokenInfo:
      "This token will be used to fork the submissions repository, to commit to it on your behalf and to make pull requests.",
    gettingUser: "Getting user data",
    gettingUserInfo: "Name and others info.",
    creatingFork: "Creating fork",
    creatingForkInfo: "Forking the submission repository.",
    createTeam: "Create team",
    joinTeam: "Join team",
    teamName: "Team name",
    teamCountries: "Team coutries",
    submit: "Submit",
    teamPrivateKey: "Team private key",
    router: {
      Home: "Home",
      Challenges: "Challenges",
      Rank: "Rank",
      Rules: "Rules",
      Settings: "Settings",
      Logged: "Getting informations"
    }
  },
  pt: {
    language: "Idioma",
    label: "Português (BR)",
    darkMode: "Modo escuro",
    navigation: "Navegação",
    news: "Notícias",
    solves: "Resolvidos",
    general: "Geral",
    team: "Time",
    country: "País",
    score: "Pontuação",
    rulesButton: "Clique aqui para ir ao site com as regras",
    username: "Username",
    members: "Membros",
    challenge: "Desafio",
    time: "Hora",
    close: "Fechar",
    gettingInformations: "Obtendo informações",
    login: "Entrar",
    logout: "Sair",
    gettingToken: "Obtendo token",
    gettingTokenInfo:
      "Esse token será usado para criar o fork do repositório de submissões, para fazer commits em seu nome e criar pull requests.",
    gettingUser: "Obtendo dados do usuário",
    gettingUserInfo: "Nome e outras informações.",
    creatingFork: "Criando fork",
    creatingForkInfo: "Criando fork do repositório de submissões.",
    createTeam: "Criar time",
    joinTeam: "Juntar-se ao time",
    teamName: "Nome do time",
    teamCountries: "Países do time",
    submit: "Enviar",
    teamPrivateKey: "Chave privada do time",
    router: {
      Home: "Início",
      Challenges: "Desafios",
      Rank: "Rank",
      Rules: "Regras",
      Settings: "Configurações",
      Logged: "Obtendo informações"
    }
  }
};
